RandomForestRegressor:
  n_estimators: [50, 100, 200, 500, 1000]
  max_depth: [null, 10, 20, 30, 40, 50]
  min_samples_split: [2, 5, 10, 20]
  min_samples_leaf: [1, 2, 4, 8]
  max_features: [null, "sqrt", "log2"]
  bootstrap: [true, false]

GradientBoostingRegressor:
  n_estimators: [50, 100, 200, 500]
  learning_rate: [0.01, 0.1, 0.2, 0.3]
  max_depth: [3, 5, 7]
  min_samples_split: [2, 5, 10]

SVR:
  C: [0.1, 1, 10, 100]
  kernel: ["linear", "rbf"]
  gamma: ["scale", "auto"]

LinearRegression:
  fit_intercept: [true, false]

GaussianNB:
  var_smoothing: [1e-9, 1e-8, 1e-7]
